In [101]:
import pandas as pd
import chess
import numpy as np

In [102]:
# test.pgn is only 1 game.
df = pd.read_csv("../tests/test.pgn", names=["data"], sep="|") # here we use sep as | because its not used anywhere in our data and we want only 1 col
df = df[
    (~df['data'].str.startswith('[')) # this tilde is negation
    | (df['data'].str.startswith('[Result'))
    | (df['data'].str.startswith('[PlyCou'))
    | (df['data'].str.startswith('[WhiteE'))
    | (df['data'].str.startswith('[BlackE'))
].reset_index(drop=True) # fix indices after column removal
df

                                                 data
0                                  [Result "1/2-1/2"]
1                                    [PlyCount "214"]
2                                   [WhiteElo "3189"]
3                                   [BlackElo "3125"]
4   1. d4 d5 2. c4 e6 3. Nc3 c6 4. e3 Nf6 5. Nf3 c...
5   Bxc5 9. Qxd8+ Kxd8 10. e4 a6 11. Bxc4 b5 12. B...
6   Bf4 Rhc8 16. h3 h6 17. Bg3 Na5 18. Rac1 Rab8 1...
7   22. Rd6 Nb6 23. Rd2 Rc5 24. a3 Rbc8 25. Bh4+ f...
8   Rxc3 Rxc3 29. Bd6+ Ke8 30. Bxb4 Rxb3 31. Bd3 N...
9   Rxd4 a5 35. Bf8 e5 36. Rg4 Bc6 37. Bh7 Kd8 38....
10  41. Bc5 Bd7 42. Bxd7 Rxd7 43. Bb6+ Ke8 44. Bxa...
11  47. Ra8 h5 48. Kf1 Rd1+ 49. Ke2 Ra1 50. Rc8 Ra...
12  Kd2 Ke6 54. Rxb5 Ra2+ 55. Ke1 Rxa3 56. Ra5 Rb3...
13  Nc6 60. Ra6 Kd5 61. Ra8 Rb4 62. Rf8 Ke6 63. Rh...
14  Kd3 Nb4+ 67. Ke2 Ke6 68. Re8+ Kf5 69. Rd8 Rc2+...
15  Kg6 73. Rh6+ Kg7 74. Rh5 Nb4 75. Ke2 Nd5 76. K...
16  79. Bc5 Rf4+ 80. Ke2 Rc4 81. Be3 Rb4 82. Ra7+ ...
17  Bc1 Rb8 86. Ke2 Nc3+ 87. Kd3 Nb5 88. Ra5 Rd8+ ...
18  Nb4 92. Bc3 Nd5 93. Bd2 Rg8 94. Ra6+ Kf5 95. K...
19  98. Ke1 Nf4 99. Bxf4 Kxf4 100. Rh7 Kg5 101. Kf...
20  104. Rf8+ Ke6 105. Rh8 Rb1+ 106. Ke2 Rb2+ 107....
21                                 [Result "1/2-1/2"]
22                                   [PlyCount "127"]
23                                  [WhiteElo "3584"]
24                                  [BlackElo "3449"]
25  1. d4 Nf6 2. c4 c5 3. Nf3 cxd4 4. Nxd4 e6 5. N...
26  Bxc3 Ne4 9. Qc2 d5 10. cxd5 Nxc3 11. Qxc3 Qxd5...
27  Rxc3 15. Rxd5 Rc1+ 16. Rd1 Rxd1+ 17. Kxd1 Nc6 ...
28  Ne7 21. Kd2 Rd8 22. e4 Bb5+ 23. Ke3 Bxe2 24. K...
29  Rd1 Rxd1 28. Nxd1 f4 29. Kf3 e5 30. Ke2 b5 31....
30  34. a4 a6 35. a5 Ne6 36. Nd1 g5 37. hxg5 Nxg5 ...
31  Kf6 41. Nd3 Kg5 42. Kd2 Kh4 43. Ke1 Nd4 44. Nx...
32  47. e5 Nd5 48. e6 h4 49. Ne1 Kf2 50. Nd3+ Kg3 ...
33  h3 54. Nxf4+ Kg3 55. Nxh3 Kxh3 56. Kd3 Kg2 57....
34  60. Ke5 Kg5 61. Ke6 Nf6 62. e8=Q Nxe8 63. Kd7 ...

In [103]:
df_work = df.copy()

df_work['data_c'] = df_work['data']
df_work['meta'] = df_work['data'].str.startswith('[')
df_work['data'] = df_work['data'].where(df_work['meta'] == True, '')
df_work['data_c'] = df_work['data_c'].where(df_work['meta'] == False, '')
df_work['data_c'] = df_work['data_c'].apply(lambda x: ' '.join(filter(lambda x: not x.endswith('.'), x.split(' ')))) #looks complicated but its just removing all move numbers by removing things that end with .

df_work

,data,data_c,meta
0,"[Result ""1/2-1/2""]",,True
1,"[PlyCount ""214""]",,True
2,"[WhiteElo ""3189""]",,True
3,"[BlackElo ""3125""]",,True
4,,d4 d5 c4 e6 Nc3 c6 e3 Nf6 Nf3 c5 Be2 dxc4 O-O ...,False
5,,Bxc5 Qxd8+ Kxd8 e4 a6 Bxc4 b5 Be2 Bb7 e5 Nd7 R...,False
6,,Bf4 Rhc8 h3 h6 Bg3 Na5 Rac1 Rab8 Nd2 Ba7 b3 Nc...,False
7,,Rd6 Nb6 Rd2 Rc5 a3 Rbc8 Bh4+ f6 exf6+ gxf6 Bg3...,False
8,,Rxc3 Rxc3 Bd6+ Ke8 Bxb4 Rxb3 Bd3 Nd5 Bg6+ Kd7 ...,False
9,,Rxd4 a5 Bf8 e5 Rg4 Bc6 Bh7 Kd8 Bd6 Rc3 Bf5 Ne7...,False
10,,Bc5 Bd7 Bxd7 Rxd7 Bb6+ Ke8 Bxa5 Nc6 Bb6 Rd3 Rg...,False
11,,Ra8 h5 Kf1 Rd1+ Ke2 Ra1 Rc8 Ra2+ Ke1 Ne7 Rc5 Ra1+,False
12,,Kd2 Ke6 Rxb5 Ra2+ Ke1 Rxa3 Ra5 Rb3 Be3 Nd5 Bc1...,False
13,,Nc6 Ra6 Kd5 Ra8 Rb4 Rf8 Ke6 Rh8 h4 Kc3 Kd5 Be3...,False
14,,Kd3 Nb4+ Ke2 Ke6 Re8+ Kf5 Rd8 Rc2+ Kf1 Nc6 Rh8...,False
15,,Kg6 Rh6+ Kg7 Rh5 Nb4 Ke2 Nd5 Kf3 Kg6 Rh8 Kf7 R...,False
16,,Bc5 Rf4+ Ke2 Rc4 Be3 Rb4 Ra7+ Ke6 Bd2 Rb2 Kd1 ...,False
17,,Bc1 Rb8 Ke2 Nc3+ Kd3 Nb5 Ra5 Rd8+ Ke3 Nd4 Bb2 ...,False
18,,Nb4 Bc3 Nd5 Bd2 Rg8 Ra6+ Kf5 Kf1 Rb8 Ra7 Rb1+ ...,False
19,,Ke1 Nf4 Bxf4 Kxf4 Rh7 Kg5 Kf1 f5 Rg7+ Kf6 Rg8 Rb5,False
20,,Rf8+ Ke6 Rh8 Rb1+ Ke2 Rb2+ Kf3 Rb4 1/2-1/2,False
21,"[Result ""1/2-1/2""]",,True
22,"[PlyCount ""127""]",,True
23,"[WhiteElo ""3584""]",,True
24,"[BlackElo ""3449""]",,True
25,,d4 Nf6 c4 c5 Nf3 cxd4 Nxd4 e6 Nc3 Bb4 Bd2 O-O ...,False
26,,Bxc3 Ne4 Qc2 d5 cxd5 Nxc3 Qxc3 Qxd5 e3 Bd7 Rd1...,False
27,,Rxc3 Rxd5 Rc1+ Rd1 Rxd1+ Kxd1 Nc6 Nc3 Kf8 Be2 ...,False
28,,Ne7 Kd2 Rd8 e4 Bb5+ Ke3 Bxe2 Kxe2 Nc6 h4 Ke7 R...,False
29,,Rd1 Rxd1 Nxd1 f4 Kf3 e5 Ke2 b5 Nc3 Nd4+ Kd3 Kd...,False
30,,a4 a6 a5 Ne6 Nd1 g5 hxg5 Nxg5 f3 Ne6 Nf2 Ke7 Kc3,False
31,,Kf6 Nd3 Kg5 Kd2 Kh4 Ke1 Nd4 Nxe5 Nc2+ Kd2 Ne3 ...,False
32,,e5 Nd5 e6 h4 Ne1 Kf2 Nd3+ Kg3 Kd1 Nc7 e7 Kxg2 Ke2,False
33,,h3 Nxf4+ Kg3 Nxh3 Kxh3 Kd3 Kg2 f4 Kf3 f5 Ne8 K...,False
34,,Ke5 Kg5 Ke6 Nf6 e8=Q Nxe8 Kd7 Kxf5 Kxe8 1/2-1/2,False

In [104]:
results = []

for d1, d2, is_meta in df_work.values:
    if is_meta:
        results += [d1]
        tmp = False
    else:
        if not tmp:
            results += [d2]
            tmp = True
        else:
            results[-1] = ' '.join([results[-1], d2])

print(results)

['[Result "1/2-1/2"]', '[PlyCount "214"]', '[WhiteElo "3189"]', '[BlackElo "3125"]', 'd4 d5 c4 e6 Nc3 c6 e3 Nf6 Nf3 c5 Be2 dxc4 O-O Nc6 dxc5 Bxc5 Qxd8+ Kxd8 e4 a6 Bxc4 b5 Be2 Bb7 e5 Nd7 Rd1 Ke7 Bf4 Rhc8 h3 h6 Bg3 Na5 Rac1 Rab8 Nd2 Ba7 b3 Nc6 Nf3 Nb4 Rd6 Nb6 Rd2 Rc5 a3 Rbc8 Bh4+ f6 exf6+ gxf6 Bg3 Rxc3 Rxc3 Rxc3 Bd6+ Ke8 Bxb4 Rxb3 Bd3 Nd5 Bg6+ Kd7 Nd4 Bxd4 Rxd4 a5 Bf8 e5 Rg4 Bc6 Bh7 Kd8 Bd6 Rc3 Bf5 Ne7 Be6 Rd3 Bc5 Bd7 Bxd7 Rxd7 Bb6+ Ke8 Bxa5 Nc6 Bb6 Rd3 Rg8+ Kf7 Ra8 h5 Kf1 Rd1+ Ke2 Ra1 Rc8 Ra2+ Ke1 Ne7 Rc5 Ra1+ Kd2 Ke6 Rxb5 Ra2+ Ke1 Rxa3 Ra5 Rb3 Be3 Nd5 Bc1 Nb4 Kd2 Nc6 Ra6 Kd5 Ra8 Rb4 Rf8 Ke6 Rh8 h4 Kc3 Kd5 Be3 Rc4+ Kd3 Nb4+ Ke2 Ke6 Re8+ Kf5 Rd8 Rc2+ Kf1 Nc6 Rh8 Rc4 Rh5+ Kg6 Rh6+ Kg7 Rh5 Nb4 Ke2 Nd5 Kf3 Kg6 Rh8 Kf7 Ra8 Rb4 Bc5 Rf4+ Ke2 Rc4 Be3 Rb4 Ra7+ Ke6 Bd2 Rb2 Kd1 Rb1+ Bc1 Rb8 Ke2 Nc3+ Kd3 Nb5 Ra5 Rd8+ Ke3 Nd4 Bb2 Nc2+ Ke2 Nb4 Bc3 Nd5 Bd2 Rg8 Ra6+ Kf5 Kf1 Rb8 Ra7 Rb1+ Ke2 Rb2 Ke1 Nf4 Bxf4 Kxf4 Rh7 Kg5 Kf1 f5 Rg7+ Kf6 Rg8 Rb5 Rf8+ Ke6 Rh8 Rb1+ Ke2 Rb2+ Kf3 Rb4 1/2-1/2', '[Result "1/2-1/2"]', '[PlyCount "127"]', '[WhiteElo "3584"]', '[BlackElo "3449"]', 'd4 Nf6 c4 c5 Nf3 cxd4 Nxd4 e6 Nc3 Bb4 Bd2 O-O a3 Bxc3 Bxc3 Ne4 Qc2 d5 cxd5 Nxc3 Qxc3 Qxd5 e3 Bd7 Rd1 Rc8 Nb5 Rxc3 Rxd5 Rc1+ Rd1 Rxd1+ Kxd1 Nc6 Nc3 Kf8 Be2 Rc8 Kc2 Ne7 Kd2 Rd8 e4 Bb5+ Ke3 Bxe2 Kxe2 Nc6 h4 Ke7 Rc1 f5 Rd1 Rxd1 Nxd1 f4 Kf3 e5 Ke2 b5 Nc3 Nd4+ Kd3 Kd6 b4 h5 a4 a6 a5 Ne6 Nd1 g5 hxg5 Nxg5 f3 Ne6 Nf2 Ke7 Kc3 Kf6 Nd3 Kg5 Kd2 Kh4 Ke1 Nd4 Nxe5 Nc2+ Kd2 Ne3 Nd3 Kg3 e5 Nd5 e6 h4 Ne1 Kf2 Nd3+ Kg3 Kd1 Nc7 e7 Kxg2 Ke2 h3 Nxf4+ Kg3 Nxh3 Kxh3 Kd3 Kg2 f4 Kf3 f5 Ne8 Kd4 Kg4 Ke5 Kg5 Ke6 Nf6 e8=Q Nxe8 Kd7 Kxf5 Kxe8 1/2-1/2']

In [105]:
df_clean = pd.DataFrame(results, columns=['data'])
df_clean['game'] = df_clean['data'].where(~df_clean['data'].str.startswith('['), '')
df_clean['data'] = df_clean['data'].str.strip('[]')
df_clean['result'] = df_clean['data'].where(df_clean['data'].str.startswith('Result'), '')
df_clean['len'] = df_clean['data'].where(df_clean['data'].str.startswith('PlyCount'), '')
df_clean['welo'] = df_clean['data'].where(df_clean['data'].str.startswith('WhiteElo'), '')
df_clean['belo'] = df_clean['data'].where(df_clean['data'].str.startswith('BlackElo'), '')

df_clean = df_clean.drop('data', axis='columns')
df_clean['result'] = df_clean['result'].apply(lambda x: x.split(' ')[-1].strip('"'))
df_clean['len'] = df_clean['len'].apply(lambda x: x.split(' ')[-1].strip('"'))
df_clean['welo'] = df_clean['welo'].apply(lambda x: x.split(' ')[-1].strip('"'))
df_clean['belo'] = df_clean['belo'].apply(lambda x: x.split(' ')[-1].strip('"'))

df_clean

                                                game   result  len  welo  belo
0                                                     1/2-1/2
1                                                              214
2                                                                   3189
3                                                                         3125
4  d4 d5 c4 e6 Nc3 c6 e3 Nf6 Nf3 c5 Be2 dxc4 O-O ...
5                                                     1/2-1/2
6                                                              127
7                                                                   3584
8                                                                         3449
9  d4 Nf6 c4 c5 Nf3 cxd4 Nxd4 e6 Nc3 Bb4 Bd2 O-O ...

In [106]:
example = {'result': '', 'len': '', 'welo': '', 'belo': '', 'game': ''}
games = []

for game, result, len, welo, belo in df_clean.values:
    if result != '':
        example['result'] = result
    if len != '':
        example['len'] = len
    if welo != '':
        example['welo'] = welo
    if belo != '':
        example['belo'] = belo
    elif game != '':
        example['game'] = game
        games += [example]
        example = {'result': '', 'len': '', 'welo': '', 'belo': '', 'game': ''}

games = pd.DataFrame(games)
games

    result  len  welo  belo                                               game
0  1/2-1/2  214  3189  3125  d4 d5 c4 e6 Nc3 c6 e3 Nf6 Nf3 c5 Be2 dxc4 O-O ...
1  1/2-1/2  127  3584  3449  d4 Nf6 c4 c5 Nf3 cxd4 Nxd4 e6 Nc3 Bb4 Bd2 O-O ...

In [107]:
print("Data quality")

print(f"Empty result: {(games['result'] == '').sum()}")
print(f"Empty len:    {(games['len'] == '').sum()}")
print(f"Empty welo:   {(games['welo'] == '').sum()}")
print(f"Empty belo:   {(games['belo'] == '').sum()}")
print(f"Empty game:   {(games['game'] == '').sum()}")

print()
display(games.dtypes)

Data quality
Empty result: 0
Empty len:    0
Empty welo:   0
Empty belo:   0
Empty game:   0

result    object
len       object
welo      object
belo      object
game      object
dtype: object

In [108]:
games['result'] = games['result'].apply(lambda x: {'1-0': 'W', '1/2-1/2': 'D', '0-1': 'B'}[x])
games = games[games['welo'] != '']
games = games[games['belo'] != '']
games = games.astype({'len': np.int32, 'welo': np.int32, 'belo': np.int32})
games = games.sample(frac=1).reset_index(drop=True)

games

  result  len  welo  belo                                               game
0      D  214  3189  3125  d4 d5 c4 e6 Nc3 c6 e3 Nf6 Nf3 c5 Be2 dxc4 O-O ...
1      D  127  3584  3449  d4 Nf6 c4 c5 Nf3 cxd4 Nxd4 e6 Nc3 Bb4 Bd2 O-O ...

In [109]:
games_filt = games[np.minimum(games['welo'], games['belo']) >= 3000].reset_index(drop=True)
games_filt

  result  len  welo  belo                                               game
0      D  214  3189  3125  d4 d5 c4 e6 Nc3 c6 e3 Nf6 Nf3 c5 Be2 dxc4 O-O ...
1      D  127  3584  3449  d4 Nf6 c4 c5 Nf3 cxd4 Nxd4 e6 Nc3 Bb4 Bd2 O-O ...

In [110]:
print("Results rates:")
display(games['result'].value_counts())
games.describe().T

Results rates:

result
D    2
Name: count, dtype: int64

      count    mean         std     min      25%     50%      75%     max
len     2.0   170.5   61.518290   127.0   148.75   170.5   192.25   214.0
welo    2.0  3386.5  279.307179  3189.0  3287.75  3386.5  3485.25  3584.0
belo    2.0  3287.0  229.102597  3125.0  3206.00  3287.0  3368.00  3449.0

In [111]:
new_games = []

for game in games_filt['game']:
    moves = game.split(' ')[:-1]

    formatted_moves = []

    for i, move in enumerate(moves):
        if i % 2 == 0:
            player = 'W'
        else:
            player = 'B'

        move_number = (i + 2) // 2

        formatted_move = f"{player}{move_number}.{move}"
        formatted_moves.append(formatted_move)

    new_game = ' '.join(formatted_moves)
    new_games.append(new_game)

games_filt['game'] = new_games
games_filt

  result  len  welo  belo                                               game
0      D  214  3189  3125  W1.d4 B1.d5 W2.c4 B2.e6 W3.Nc3 B3.c6 W4.e3 B4....
1      D  127  3584  3449  W1.d4 B1.Nf6 W2.c4 B2.c5 W3.Nf3 B3.cxd4 W4.Nxd...